# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.

#             [list source [file join $dir lib project3x project.tcl]]; \
#            [list source [file join $dir lib project3x lib_projectUpdate.tcl]]; \
#                \

package ifneeded bikeFrame  0.00 "\
                \
            [list source [file join $dir     bikeFrame.tcl]]; \
                \
            [list source [file join $dir lib mixinMethodProtoypes.tcl]]; \
                \
            [list source [file join $dir lib abstractFrame.tcl]]; \
            [list source [file join $dir lib abstractComponent.tcl]]; \
            [list source [file join $dir lib abstractProvidePart.tcl]]; \
                \
            [list source [file join $dir lib classFrameFactory.tcl]]; \
            [list source [file join $dir lib classDiamondFrame.tcl]]; \
                \
            [list source [file join $dir lib frameLug   abstractLug.tcl]]; \
                \
            [list source [file join $dir lib frameLug   provideBottomBracket.tcl]]; \
            [list source [file join $dir lib frameLug   provideRearDropout.tcl]]; \
            [list source [file join $dir lib frameLug   classBottomBracket.tcl]]; \
            [list source [file join $dir lib frameLug   classRearDropout.tcl]]; \
                \
            [list source [file join $dir lib frameTube  abstractTube.tcl]]; \
            [list source [file join $dir lib frameTube  facadeTubeMiter.tcl]]; \
                \
            [list source [file join $dir lib frameTube  provideDownTube.tcl]]; \
            [list source [file join $dir lib frameTube  provideHeadTube.tcl]]; \
            [list source [file join $dir lib frameTube  provideSeatTube.tcl]]; \
            [list source [file join $dir lib frameTube  provideTopTube.tcl]]; \
            [list source [file join $dir lib frameTube  provideChainStay.tcl]]; \
            [list source [file join $dir lib frameTube  provideSeatStay.tcl]]; \
            [list source [file join $dir lib frameTube  classHeadTube.tcl]]; \
            [list source [file join $dir lib frameTube  classChainStay.tcl]]; \
                \
            [list source [file join $dir lib _init.tcl]]; \
        "
        #
        #   [list source [file join $dir lib frameTube  classDownTube.tcl]]; \
        #   [list source [file join $dir lib frameTube  classSeatTube.tcl]]; \
        #   [list source [file join $dir lib frameTube  classTopTube.tcl]]; \
        #   [list source [file join $dir lib frameTube  classSeatStay.tcl]]; \
        #
