# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.

package ifneeded cad4tcl  0.01 " \
                \
            [list source [file join $dir     cad4tcl.tcl]]
            [list source [file join $dir lib cad4tcl_tdom.tcl]]
            [list source [file join $dir lib cad4tcl_utility.tcl]]
            [list source [file join $dir lib vectorfont.tcl]]
                \
            [list source [file join $dir lib classCanvasFactory.tcl]]
                \
            [list source [file join $dir lib classCanvas__Base.tcl]]
            [list source [file join $dir lib classCanvas.tcl]]
                \
            [list source [file join $dir lib classItemIF__Super.tcl]]
            [list source [file join $dir lib classItemIF_Canvas.tcl]]
            [list source [file join $dir lib classItemIF_PathCanvas.tcl]]
                \
            [list source [file join $dir lib classExtension_SVG__Super.tcl]]
            [list source [file join $dir lib classExtension_SVG_Canvas.tcl]]
            [list source [file join $dir lib classExtension_SVG_PathCanvas.tcl]]
                \
            [list source [file join $dir lib classExtension_DXF__Super.tcl]]
            [list source [file join $dir lib classExtension_DXF_Canvas.tcl]]
            [list source [file join $dir lib classExtension_DXF_PathCanvas.tcl]]
                \
            [list source [file join $dir lib classDimensionFactory.tcl]]
            [list source [file join $dir lib classDimension.tcl]]
                \
            [list source [file join $dir lib cad4tcl_Image.tcl]]
                \
    "

    # [list source [file join $dir lib canvasCAD_svg_path.tcl]]
    # [list source [file join $dir lib classExtension_SVG_PathCanvas.tcl]]
    # [list source [file join $dir lib canvasCAD_stage.tcl]]
    # [list source [file join $dir lib dimension.tcl]]
    # [list source [file join $dir lib canvasCAD_IO.tcl]]
    # [list source [file join $dir lib canvasCAD_exportPS.tcl]]
    # [list source [file join $dir lib canvasCAD_configCorner.tcl]]
    # [list source [file join $dir lib classCanvasFactory.tcl]]
    # [list source [file join $dir lib classCanvas.tcl]]
    # [list source [file join $dir lib _init.tcl]]        
    
    # [list source [file join $dir lib canvasCAD_binding.tcl]]
            