# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.

#             [list source [file join $dir lib project3x project.tcl]]; \
#            [list source [file join $dir lib project3x lib_projectUpdate.tcl]]; \
#                \

package ifneeded bikeComponent 0.01 "\
            [list source [file join $dir     bikeComponent.tcl]]; \
            [list source [file join $dir lib class_AbstractComponent.tcl]]; \
            [list source [file join $dir lib class_Component.tcl]]; \
            [list source [file join $dir lib class_ComponentBasic.tcl]]; \
            [list source [file join $dir lib class_ComponentBare.tcl]]; \
                \
            [list source [file join $dir lib fork class_Fork.tcl]]; \
            [list source [file join $dir lib fork class_ForkCustomSteel.tcl]]; \
            [list source [file join $dir lib fork comp_ForkComposite.tcl]]; \
            [list source [file join $dir lib fork comp_ForkSuspension.tcl]]; \
            [list source [file join $dir lib fork comp_ForkSupplier.tcl]]; \
            [list source [file join $dir lib fork comp_ForkCustomSteelBent.tcl]]; \
            [list source [file join $dir lib fork comp_ForkCustomSteelStraight.tcl]]; \
            [list source [file join $dir lib fork comp_ForkCustomSteelMAX.tcl]]; \
            [list source [file join $dir lib fork comp_ForkBlade.tcl]]; \
            [list source [file join $dir lib fork comp_ForkSteerer.tcl]]; \
            [list source [file join $dir lib fork ForkStrategy.tcl]]; \
                \
            [list source [file join $dir lib comp_Fork.tcl]]; \
                \
            [list source [file join $dir lib _bare BottleCage.tcl]]; \
            [list source [file join $dir lib _bare CrankSet.tcl]]; \
            [list source [file join $dir lib _bare Fender.tcl]]; \
            [list source [file join $dir lib _bare HeadSet.tcl]]; \
            [list source [file join $dir lib _bare RearHub.tcl]]; \
            [list source [file join $dir lib _bare SeatPost.tcl]]; \
            [list source [file join $dir lib _bare Stem.tcl]]; \                
                \
            [list source [file join $dir lib comp_BottleCage.tcl]]; \
            [list source [file join $dir lib comp_CrankSet.tcl]]; \
            [list source [file join $dir lib comp_HeadSet.tcl]]; \
            [list source [file join $dir lib comp_RearHub.tcl]]; \
            [list source [file join $dir lib comp_SeatPost.tcl]]; \
            [list source [file join $dir lib comp_Stem.tcl]]; \
                \
            [list source [file join $dir lib comp_FrontBrake.tcl]]; \
            [list source [file join $dir lib comp_FrontFender.tcl]]; \
            [list source [file join $dir lib comp_RearBrake.tcl]]; \
            [list source [file join $dir lib comp_RearDropout.tcl]]; \
            [list source [file join $dir lib comp_RearFender.tcl]]; \
            [list source [file join $dir lib comp_Saddle.tcl]]; \
                \
            [list source [file join $dir lib lib_libWidget.tcl]]; \
                \
            [list source [file join $dir lib IF_Component.tcl]]; \
        "

# [list source [file join $dir lib class_CompLibrary.tcl]]; \
                    
# [list source [file join $dir lib comp_RearDerailleur.tcl]]; \
# [list source [file join $dir lib fender class_Fender.tcl]]; \
# [list source [file join $dir lib fender FrontFender.tcl]]; \
# [list source [file join $dir lib fender RearFender.tcl]]; \

# [list source [file join $dir lib lib_Fork.tcl]]; \
# [list source [file join $dir lib lib_tube.tcl]]; \
       

# [list source [file join $dir lib __a comp_Fork.tcl]]; \

# [list source [file join $dir lib __a superclass_partAbstract.tcl]]; \
# [list source [file join $dir lib __a class_partComponent.tcl]]; \
   
# [list source [file join $dir lib lib_bikeGeometryResult.tcl]]; \      
# [list source [file join $dir lib fruit.tcl]]; 
# [list source [file join $dir lib lib_geometry.tcl]]; \
# [list source [file join $dir lib lib_components.tcl]]; \
# [list source [file join $dir lib lib_frametubes.tcl]]; \
# [list source [file join $dir lib lib_CrankSet.tcl]]; \
# [list source [file join $dir lib lib_HeadSet.tcl]]; \
# [list source [file join $dir lib lib_RearHub.tcl]]; \
# [list source [file join $dir lib lib_SeatPost.tcl]]; \
# [list source [file join $dir lib lib_Stem.tcl]]; \
# [list source [file join $dir lib lib_Fender.tcl]]; \
# [list source [file join $dir lib lib_BottleCage.tcl]]; \
                     
            