# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.

package ifneeded tubeMiter  0.12 "\
        [list source [file join $dir     tubeMiter.tcl] ]; \
            \
        [list source [file join $dir lib abstractProfile.tcl] ]; \
        [list source [file join $dir lib ovalProfile.tcl] ]; \
        [list source [file join $dir lib roundProfile.tcl] ]; \
            \
        [list source [file join $dir lib abstractTubeMiter.tcl] ]; \
        [list source [file join $dir lib coneMiter.tcl] ]; \
        [list source [file join $dir lib cylinderMiter.tcl] ]; \
        [list source [file join $dir lib frustumMiter.tcl] ]; \
        [list source [file join $dir lib planeMiter.tcl] ]; \
    "