# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.

package ifneeded   myGUI  0.01 "\ 
            \
        [list source  [file join $dir myGUI.tcl]]
            \
        [list source  [file join $dir lib mvc   _view.tcl]]
        [list source  [file join $dir lib mvc   lib__view_configPanel.tcl]]
        [list source  [file join $dir lib mvc   lib__view_Edit.tcl]]
        [list source  [file join $dir lib mvc   lib__view_EditFactory.tcl]]
        [list source  [file join $dir lib mvc   lib__view_EditComponent.tcl]]
            \
        [list source  [file join $dir lib mvc   _model.tcl]]
        [list source  [file join $dir lib mvc   model_Info.tcl]]
        [list source  [file join $dir lib mvc   model_Edit.tcl]]
        [list source  [file join $dir lib mvc   model_TubeMiter.tcl]]
        [list source  [file join $dir lib mvc   model_XY.tcl]]
        [list source  [file join $dir lib mvc   model_XZ.tcl]]
            \
        [list source  [file join $dir lib mvc   _control.tcl]]
        [list source  [file join $dir lib mvc   lib__control.changeList.tcl]]
            \
        [list source  [file join $dir lib       lib__gui.tcl]]
        [list source  [file join $dir lib       lib__export.tcl]]
        [list source  [file join $dir lib       lib_cvCustom.tcl]]
        [list source  [file join $dir lib       lib_cvCustom__update.tcl]]
        [list source  [file join $dir lib       lib_reference.tcl]]
        [list source  [file join $dir lib       lib_dimension.tcl]]
        [list source  [file join $dir lib       lib_rearMockup.tcl]]
        [list source  [file join $dir lib       lib_tubeMiter.tcl]]
        [list source  [file join $dir lib       lib_compLibrary.tcl]]
        [list source  [file join $dir lib       lib_infoPanel.tcl]]
        [list source  [file join $dir lib       lib_cfgReport.tcl]]
        [list source  [file join $dir lib       lib_rendering.tcl]]
        [list source  [file join $dir lib       lib_plugIn.tcl]]
        [list source  [file join $dir lib       lib_test.tcl]]
        [list source  [file join $dir lib       lib_debug.tcl]]
            \
        [list source  [file join $dir lib       classAbstractBase.tcl]]
            \
        [list source  [file join $dir lib modelAdapter  classModelContext.tcl]]
        [list source  [file join $dir lib modelAdapter  classStrategyAdapterModel.tcl]]
        [list source  [file join $dir lib modelAdapter  classAdapterBikeModel.tcl]]
        [list source  [file join $dir lib modelAdapter  classBikeModel_Mapping.tcl]]
            \
        [list source  [file join $dir lib modelAdapter  _modelAdapter.tcl]]
        [list source  [file join $dir lib modelAdapter  _init.tcl]]
            \
   "
   
 # [list source  [file join $dir lib       lib_dimension_BaseGeometry.tcl]]; \
 # [list source  [file join $dir lib       lib_cvCustom_FrameJig.tcl]]; \
                
 # [list source  [file join $dir lib       lib__tool.tcl]]; \
 # [list source  [file join $dir lib mvc   __mvc.tcl]]; \
 # [list source  [file join $dir lib mvc   _mvc.tcl]]; \
        
        
 # .. unused since 3.1.00
 # [list source  [file join $dir lib_control.tcl]]; 
 # [list source  [file join $dir lib_frame_ref_geometry.tcl]]; \ 
 # [list source  [file join $dir lib_projectUpdate.tcl]]; \
         
 # [list source  [file join $dir model    classDomainMappingStrategy.tcl]]; \
 # [list source  [file join $dir model    classModelContext.tcl]]; \
 # [list source  [file join $dir model    classAdapterBikeGeometry.tcl]]; \
 # [list source  [file join $dir model    classAdapterBikeModel.tcl]]; \
 # [list source  [file join $dir model    classMapContext.tcl]]; \
 # [list source  [file join $dir model    classBikeGeometry.tcl]]; \
 # [list source  [file join $dir model    classBikeModel.tcl]]; \
 # [list source  [file join $dir model    lib__model.persistence.tcl]]; \
