# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.

#            [list source [file join $dir lib project3x project.tcl]]; \
#            [list source [file join $dir lib project3x lib_projectUpdate.tcl]]; \
#                \

package ifneeded bikeModel  0.03 " \
            [list source [file join $dir     bikeModel.tcl]]; \
                \
            [list source [file join $dir lib superclass_partAbstract.tcl]]; \
            [list source [file join $dir lib class_partSimple.tcl]]; \
            [list source [file join $dir lib class_factoryPart.tcl]]; \
                \
        "

# [list source [file join $dir lib class_partComponent.tcl]]; \
# [list source [file join $dir lib ns_geometry.tcl]]; \
# [list source [file join $dir lib comp_HeadSet.tcl]]; \
# [list source [file join $dir lib IF_DiamondFrame.tcl]]; \
# [list source [file join $dir lib classBikeComponent.tcl]]; \            
# [list source [file join $dir lib lib_bikeGeometryResult.tcl]]; \      
# [list source [file join $dir lib fruit.tcl]]; 
# [list source [file join $dir lib lib_geometry.tcl]]; \
# [list source [file join $dir lib lib_components.tcl]]; \
# [list source [file join $dir lib lib_frametubes.tcl]]; \
            